#!/usr/bin/env bash
set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"
output_file="$repo_root/data/repo-activity.yaml"
max_points=80

if [[ "$(git -C "$repo_root" rev-parse --is-shallow-repository)" == "true" ]]; then
  echo "Cannot build accurate repository activity from a shallow clone." >&2
  exit 1
fi

total="$(git -C "$repo_root" rev-list --count HEAD)"
if [[ "$total" -eq 0 ]]; then
  echo "Cannot build repository activity without commits." >&2
  exit 1
fi

history_file="$(mktemp)"
trap 'rm -f "$history_file"' EXIT

git -C "$repo_root" log --reverse --format='%cs %h' HEAD | tail -n "$max_points" > "$history_file"

awk -v total="$total" '
  BEGIN {
    columns = 20
    x_start = 5.5
    x_step = 11
    y_start = 6
    y_step = 10
  }
  {
    date[NR] = $1
    hash[NR] = $2
  }
  END {
    shown = NR
    print "# Generated by scripts/build-repo-activity.sh; do not edit by hand."
    print "total: " total
    print "shown: " shown
    print "first_date: \"" date[1] "\""
    print "last_date: \"" date[shown] "\""
    print "points:"

    for (i = 1; i <= shown; i++) {
      column = (i - 1) % columns
      row = int((i - 1) / columns)
      x = x_start + (column * x_step)
      y = y_start + (row * y_step)
      printf "  - x: %.1f\n", x
      printf "    y: %.1f\n", y
      print "    date: \"" date[i] "\""
      print "    hash: \"" hash[i] "\""
    }
  }
' "$history_file" > "$output_file"

echo "Generated $output_file with $(wc -l < "$history_file" | tr -d ' ') of $total commits."
